{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-service.serviceAccountName" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052747538895:role/eks-dynamodb-role-irsa
{{- end -}}

